---
- name: Generate an OpenSSL certificate signed by our CA
  openssl_certificate:
    path: "{{ ssl_certs_cert_path }}"
    privatekey_path: "{{ ssl_certs_privkey_path }}"
    privatekey_passphrase: "{{ ssl_certs_passphrase }}"
    csr_path: "{{ ssl_certs_csr_path }}"
    provider: ownca
    ownca_path: "{{ ssl_certs_ca_cert_path }}"
    ownca_privatekey_path: "{{ ssl_certs_ca_privatekey_path }}"
    ownca_privatekey_passphrase: "{{ ssl_certs_ca_passphrase }}"
    force: yes
  delegate_to: 127.0.0.1

- name: Verify that an existing certificate was issued by the our root CA and is currently still valid
  openssl_certificate:
    path: "{{ ssl_certs_cert_path }}"
    provider: assertonly
    issuer:
      C: "{{ ssl_certs_ca_country }}"
      L: "{{ ssl_certs_ca_locality }}"
      O: "{{ ssl_certs_ca_organization }}"
      OU: "{{ ssl_certs_ca_organizational_unit }}"
    has_expired: False
  delegate_to: 127.0.0.1
