---
- name: Ensure OpenSSL is installed
  package: name=openssl state=present
  tags: [ssl-certs,packages]
  delegate_to: 127.0.0.1

- name: Ensure pip dependencies are present
  run_once: True
  pip:
    name: ["pyopenssl", "pexpect"]
    state: latest
    extra_args: --user
  delegate_to: 127.0.0.1

- name: Ensure ssl folder exist
  file:
    path: "{{ ssl_certs_path }}"
    state: directory
    owner: "{{ ssl_certs_path_owner }}"
    group: "{{ ssl_certs_path_group }}"
    mode: "{{ ssl_certs_mode }}"
  tags: [ssl-certs,configuration]
  delegate_to: 127.0.0.1