---
- name: Ensure OpenSSL is installed
  package: name=openssl state=present
  delegate_to: 127.0.0.1

- name: Ensure pip dependencies are present
  run_once: True
  pip:
    name: ["pyopenssl", "pexpect"]
    state: latest
    extra_args: --user
  delegate_to: 127.0.0.1

- name: Ensure local ssl folder exist
  file:
    path: "{{ ssl_certs_path }}"
    state: directory
    # Is this relevant? Can't this be removed?
    owner: "{{ ssl_certs_path_owner }}"
    group: "{{ ssl_certs_path_group }}"
    mode: "{{ ssl_certs_mode }}"
  delegate_to: 127.0.0.1