---
  - name: Prepare node environment
    include_tasks: install_dependencies.yml

  - name: Generate private key
    openssl_privatekey:
      path: "{{ ssl_certs_privkey_path }}"
      passphrase: "{{ ssl_certs_passphrase }}"
      cipher: des3
      force: True
    delegate_to: 127.0.0.1

  - name: Generate a Certificate Sign Request
    openssl_csr:
      path: "{{ ssl_certs_csr_path }}"
      mode: "{{ ssl_certs_mode }}"
      privatekey_path: "{{ ssl_certs_privkey_path }}"
      privatekey_passphrase: "{{ ssl_certs_passphrase }}"
      country_name: "{{ ssl_certs_country }}"
      locality_name: "{{ ssl_certs_locality }}"
      organization_name: "{{ ssl_certs_organization }}"
      organizational_unit_name: "{{ ssl_certs_organizational_unit }}"
      common_name: "{{ ssl_certs_common_name }}"
      email_address: "{{ ssl_certs_email }}"
      subject_alt_name:
      - "DNS:{{ ansible_fqdn }}"
      - "IP:{{ ansible_default_ipv4.address }}"
    delegate_to: 127.0.0.1

  - name: Generate certificates signed by our CA
    when: amq_ssl_certs_self_signed == False
    include: generate_ca_signed.yml

  - name: Generate selfsigned certificate
    when: amq_ssl_certs_self_signed == True
    include: generate_self_signed.yml

  - debug:
      msg: "path: {{ ssl_cert_pkcs12_path }}
                  passphrase: {{ amq_keystore_password }}
                  friendly_name: {{ amq_ssl_cert_pkcs12_name_alias }}
                  privatekey_path: {{ ssl_certs_privkey_path }}
                  privatekey_passphrase: {{ ssl_certs_passphrase }}
                  certificate_path: {{ ssl_certs_csr_path }} "

  - name: Generate PKCS12 file
    openssl_pkcs12:
      action: export
      path: "{{ ssl_cert_pkcs12_path }}"
      passphrase: "{{ amq_keystore_password }}"
      friendly_name: "{{ amq_ssl_cert_pkcs12_name_alias }}"
      privatekey_path: "{{ ssl_certs_privkey_path }}"
      privatekey_passphrase: "{{ ssl_certs_passphrase }}"
      certificate_path: "{{ ssl_certs_cert_path }}"
      force: yes
    delegate_to: 127.0.0.1

  - name: Copy generated SSL files to remote nodes
    when: amq_copy_generated_files == True
    include: distribute_files.yml

  - name: Add certificate & key to local keystore
    when: amq_keytool_enabled == True
    include: keytool.yml

  - name: Create README file with location and passwords
    when: amq_keytool_enabled == true
    template:
      src: templates/readme_template.j2
      dest: "{{ amq_ssl_dir_path }}/readme"
      mode: 0644
