---
  - name: Ensure OpenSSL is installed
    package: name=openssl state=present
    tags: [ssl-certs,packages]
    delegate_to: 127.0.0.1


  - name: Ensure pip dependencies are present
    pip:
      name: "{{ item }}"
      state: latest
      extra_args: --user
    with_items:
      - pyopenssl
      - pexpect
    delegate_to: 127.0.0.1


  - name: Ensure ssl folder exist
    file:
      path: "{{ ssl_certs_path }}"
      state: directory
      owner: "{{ ssl_certs_path_owner }}"
      group: "{{ ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
    tags: [ssl-certs,configuration]
    delegate_to: 127.0.0.1

  - include: generate_modules.yml

  - name: Copy SSL private key to node
    copy:
      src: "{{ ssl_certs_privkey_path }}"
      dest: "{{ amq_ssl_key_path }}"
      owner: "{{ amq_ssl_certs_path_owner }}"
      group: "{{ amq_ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
      force: true

  - name: Copy signed SSL certificate file
    copy:
      src: "{{ ssl_certs_cert_path }}"
      dest: "{{ amq_ssl_cert_path }}"
      owner: "{{ amq_ssl_certs_path_owner }}"
      group: "{{ amq_ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
      force: true

  - name: Copy CA certificate file
    copy:
      src: "{{ ssl_certs_ca_cert_path }}"
      dest: "{{ amq_ssl_ca_cert_path }}"
      owner: "{{ amq_ssl_certs_path_owner }}"
      group: "{{ amq_ssl_certs_path_group }}"
      mode: "{{ ssl_certs_mode }}"
      force: true
